ds1="../datasets/1/1.fb2"
ds2="../datasets/2/2.fb2"
ds3="../datasets/3/3.fb2"
places_path="../dictionaries/places.txt"
profs_path="../dictionaries/professions.txt"
preps_path="../dictionaries/directionprep.txt"
stop_path="../dictionaries/stopwords.txt"
